version: '3'
services:
  server:
    build: ./openresty
    image: server:1.0
    depends_on:
    - katari_web
    ports:
    - 443:9443
    - 80:9000

  katari_web:
    build: .
    volumes:
      - .:/app/
    depends_on:
      - katari_mongo

  katari_mongo:
    image: mongo:4.2
    volumes:
      - ./db/:/data/db