version: '3'
services:
  katari_web:
    build: .
    volumes:
      - .:/app/
    ports:
      - "4567:4567"
    depends_on:
      - katari_mongo

  katari_mongo:
    image: mongo:4.2
    volumes:
      - ./db/:/data/db