version: '3'
services:
  server:
    build: ./openresty
    image: server:1.0
    depends_on:
    - katari_web
    ports:
    - 9000:9000
    
  katari_web:
    build: .
    volumes:
      - .:/app/
    ports:
      - "4567:4567"
    depends_on:
      - katari_mongo

  katari_mongo:
    image: mongo:4.2
    volumes:
      - ./db/:/data/db